// Facet taxonomy + tags for the Learn recipe cards (oxjob #354, Jason-approved
// 2026-07-28). Facets are TAGS, not categories: a card carries 0..n values per
// facet. Filtering is OR within a facet, AND across facets.
//
// Lives here (not in content frontmatter) for the same reason as nav.ts: the
// content files are regenerated by the migration scripts, and slugs are the
// stable key. Values with zero cards still render (muted) — the library is
// growing and Agents/Snapshot recipes are coming.
//
// Terminology is deliberately OpenAlex-native ("Sources", "Aboutness") — we
// teach users our vocabulary as they go.

export interface FacetValue {
  id: string;
  label: string;
}
export interface Facet {
  key: string;
  label: string;
  values: FacetValue[];
}

export const FACETS: Facet[] = [
  {
    key: 'task',
    label: 'Task',
    values: [
      { id: 'count', label: 'Count' },
      { id: 'find', label: 'Find' },
      { id: 'fix', label: 'Fix' },
      { id: 'map', label: 'Map' },
    ],
  },
  {
    key: 'variable',
    label: 'Variable',
    values: [
      { id: 'output', label: 'Output volume' },
      { id: 'citations', label: 'Citations' },
      { id: 'open-access', label: 'Open Access' },
      { id: 'collaboration', label: 'Collaboration' },
      { id: 'aboutness', label: 'Aboutness' },
      { id: 'funding', label: 'Funding & costs' },
    ],
  },
  {
    key: 'entity',
    label: 'Entity',
    values: [
      { id: 'institutions', label: 'Institutions' },
      { id: 'authors', label: 'Authors' },
      { id: 'sources', label: 'Sources' },
      { id: 'funders', label: 'Funders' },
    ],
  },
  {
    key: 'interface',
    label: 'Interface',
    values: [
      { id: 'web', label: 'Web' },
      { id: 'api', label: 'API' },
      { id: 'agents', label: 'Agents' },
      { id: 'snapshot', label: 'Snapshot' },
    ],
  },
];

type CardTags = Partial<Record<'task' | 'variable' | 'entity' | 'interface', string[]>>;

export const CARD_FACETS: Record<string, CardTags> = {
  'analyze-a-funders-portfolio': {
    task: ['map'],
    variable: ['output'],
    entity: ['funders'],
    interface: ['api'],
  },
  'audit-an-author-profiles-works': {
    task: ['fix'],
    entity: ['authors'],
    interface: ['api'],
  },
  'break-down-of-my-institutions-outputs-by-subject-area-subfield': {
    task: ['count'],
    variable: ['output', 'aboutness'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'check-if-a-journals-works-are-in-openalex': {
    task: ['fix', 'count'],
    variable: ['output'],
    entity: ['sources'],
    interface: ['web'],
  },
  'count-incoming-citations-to-any-results-set': {
    task: ['count'],
    variable: ['citations'],
    interface: ['web'],
  },
  'estimate-the-apc-fees-my-institution-has-paid-to-make-research-open-ac': {
    task: ['count'],
    variable: ['funding', 'open-access'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'find-collaborators': {
    task: ['find'],
    variable: ['collaboration'],
    entity: ['authors', 'institutions'],
    interface: ['api'],
  },
  'find-most-cited-journals': {
    task: ['count', 'find'],
    variable: ['citations'],
    entity: ['institutions', 'sources'],
    interface: ['api'],
  },
  'how-many-of-each-type-of-output-does-my-institution-have': {
    task: ['count'],
    variable: ['output'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'how-many-outputs-does-my-institution-have': {
    task: ['count'],
    variable: ['output'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'how-much-is-my-institutions-work-cited': {
    task: ['count'],
    variable: ['citations'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'identify-other-institutions-that-collaborate-with-researchers-from-my': {
    task: ['find'],
    variable: ['collaboration'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'map-an-sdg-research-landscape': {
    task: ['map'],
    variable: ['aboutness'],
    interface: ['api'],
  },
  'quick-api-recipes': {
    task: ['count', 'find'],
    interface: ['api'],
  },
  'track-open-access-trends': {
    task: ['map', 'count'],
    variable: ['open-access'],
    interface: ['api'],
  },
  'what-percentage-of-my-institutions-outputs-are-open-access-oa': {
    task: ['count'],
    variable: ['open-access'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'which-journals-do-researchers-at-my-institution-publish-in': {
    task: ['count', 'find'],
    variable: ['output'],
    entity: ['institutions', 'sources'],
    interface: ['web'],
  },
  'which-of-my-institutions-outputs-are-contributions-to-un-sustainable-d': {
    task: ['count'],
    variable: ['aboutness'],
    entity: ['institutions'],
    interface: ['web'],
  },
};

export function facetsFor(slug: string): CardTags {
  return CARD_FACETS[slug] ?? {};
}
