// Facet taxonomy + tags for the two "bucket" tabs (oxjob #354, Jason-approved
// 2026-07-28; FAQ added Pass U 2026-08-06). Recipes and FAQ are flat buckets
// of articles you filter, not curated hierarchies — facets are TAGS, not
// categories: a card carries 0..n values per facet. Filtering is OR within a
// facet, AND across facets.
//
// Lives here (not in content frontmatter) for the same reason as nav.ts: the
// content files are regenerated by the migration scripts, and slugs are the
// stable key. Values with zero cards still render (muted) — the library is
// growing and Agents/Snapshot recipes are coming.
//
// Terminology is deliberately OpenAlex-native ("Sources", "Aboutness") — we
// teach users our vocabulary as they go.
//
// The Entity and Interface axes are shared vocabulary between the two tabs
// (each tab lists only the values its articles use); Recipes' Task/Variable
// axes are analysis-shaped and don't fit FAQ articles, which get a Topic axis
// instead (Pass U call).

export interface FacetValue {
  id: string;
  label: string;
}
export interface Facet {
  key: string;
  label: string;
  values: FacetValue[];
}

export const FACETS: Facet[] = [
  {
    key: 'task',
    label: 'Task',
    values: [
      { id: 'count', label: 'Count' },
      { id: 'find', label: 'Find' },
      { id: 'fix', label: 'Fix' },
      { id: 'map', label: 'Map' },
    ],
  },
  {
    key: 'variable',
    label: 'Variable',
    values: [
      { id: 'output', label: 'Output volume' },
      { id: 'citations', label: 'Citations' },
      { id: 'open-access', label: 'Open Access' },
      { id: 'collaboration', label: 'Collaboration' },
      { id: 'aboutness', label: 'Aboutness' },
      { id: 'funding', label: 'Funding & costs' },
    ],
  },
  {
    key: 'entity',
    label: 'Entity',
    values: [
      { id: 'institutions', label: 'Institutions' },
      { id: 'authors', label: 'Authors' },
      { id: 'sources', label: 'Sources' },
      { id: 'funders', label: 'Funders' },
    ],
  },
  {
    key: 'interface',
    label: 'Interface',
    values: [
      { id: 'web', label: 'Web' },
      { id: 'api', label: 'API' },
      { id: 'oql', label: 'OQL' },
      { id: 'agents', label: 'Agents' },
      { id: 'snapshot', label: 'Snapshot' },
    ],
  },
];

type CardTags = Partial<Record<'task' | 'variable' | 'entity' | 'interface', string[]>>;

export const CARD_FACETS: Record<string, CardTags> = {
  'analyze-a-funders-portfolio': {
    task: ['map'],
    variable: ['output'],
    entity: ['funders'],
    interface: ['api'],
  },
  'audit-an-author-profiles-works': {
    task: ['fix'],
    entity: ['authors'],
    interface: ['api'],
  },
  'break-down-of-my-institutions-outputs-by-subject-area-subfield': {
    task: ['count'],
    variable: ['output', 'aboutness'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'check-if-a-journals-works-are-in-openalex': {
    task: ['fix', 'count'],
    variable: ['output'],
    entity: ['sources'],
    interface: ['web'],
  },
  'count-incoming-citations-to-any-results-set': {
    task: ['count'],
    variable: ['citations'],
    interface: ['web'],
  },
  'estimate-the-apc-fees-my-institution-has-paid-to-make-research-open-ac': {
    task: ['count'],
    variable: ['funding', 'open-access'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'find-collaborators': {
    task: ['find'],
    variable: ['collaboration'],
    entity: ['authors', 'institutions'],
    interface: ['api'],
  },
  'find-most-cited-journals': {
    task: ['count', 'find'],
    variable: ['citations'],
    entity: ['institutions', 'sources'],
    interface: ['api'],
  },
  'how-many-of-each-type-of-output-does-my-institution-have': {
    task: ['count'],
    variable: ['output'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'how-many-outputs-does-my-institution-have': {
    task: ['count'],
    variable: ['output'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'how-much-is-my-institutions-work-cited': {
    task: ['count'],
    variable: ['citations'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'identify-other-institutions-that-collaborate-with-researchers-from-my': {
    task: ['find'],
    variable: ['collaboration'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'map-an-sdg-research-landscape': {
    task: ['map'],
    variable: ['aboutness'],
    interface: ['api'],
  },
  'quick-api-recipes': {
    task: ['count', 'find'],
    interface: ['api'],
  },
  'track-open-access-trends': {
    task: ['map', 'count'],
    variable: ['open-access'],
    interface: ['api'],
  },
  'what-percentage-of-my-institutions-outputs-are-open-access-oa': {
    task: ['count'],
    variable: ['open-access'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'which-journals-do-researchers-at-my-institution-publish-in': {
    task: ['count', 'find'],
    variable: ['output'],
    entity: ['institutions', 'sources'],
    interface: ['web'],
  },
  'which-of-my-institutions-outputs-are-contributions-to-un-sustainable-d': {
    task: ['count'],
    variable: ['aboutness'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'systematic-reviews-with-oql': {
    task: ['find'],
    interface: ['oql', 'web', 'api'],
  },
  // Bulk-data + Unpaywall recipes (moved in from Docs, rewrite Pass H)
  'download-to-your-machine': {
    task: ['map'],
    interface: ['snapshot'],
  },
  'how-do-i-read-jsonl-files': {
    task: ['map'],
    interface: ['snapshot'],
  },
  'how-do-i-use-the-title-search-api': {
    task: ['find'],
    variable: ['open-access'],
    interface: ['api'],
  },
  'how-do-i-make-the-unpaywall-extension-work-on-my-site': {
    task: ['fix'],
    variable: ['open-access'],
    interface: ['web'],
  },
};

export function facetsFor(slug: string): CardTags {
  return CARD_FACETS[slug] ?? {};
}

// --- FAQ tab (Pass U) ---

export const HELP_FACETS: Facet[] = [
  {
    key: 'topic',
    label: 'Topic',
    values: [
      { id: 'about', label: 'About OpenAlex' },
      { id: 'how-we-build-it', label: 'How we build it' },
      { id: 'fixing-errors', label: 'Fixing errors' },
      { id: 'indexing', label: 'Getting indexed' },
      { id: 'ids', label: 'Finding IDs' },
      { id: 'searching', label: 'Searching & counts' },
      { id: 'exporting', label: 'Exports & integrations' },
      { id: 'supporters', label: 'Supporter benefits' },
    ],
  },
  {
    key: 'entity',
    label: 'Entity',
    values: [
      { id: 'works', label: 'Works' },
      { id: 'authors', label: 'Authors' },
      { id: 'sources', label: 'Sources' },
      { id: 'institutions', label: 'Institutions' },
      { id: 'publishers', label: 'Publishers' },
    ],
  },
  {
    key: 'interface',
    label: 'Interface',
    values: [
      { id: 'web', label: 'Web' },
      { id: 'api', label: 'API' },
    ],
  },
];

type HelpTags = Partial<Record<'topic' | 'entity' | 'interface', string[]>>;

export const HELP_CARD_FACETS: Record<string, HelpTags> = {
  'about-us': { topic: ['about'] },
  'how-can-i-cite-openalex': { topic: ['about'] },
  'pricing': { topic: ['about'] },
  'what-is-openalexs-sustainability-model': { topic: ['about'] },
  'whats-on-openalexs-roadmap': { topic: ['about'] },
  'how-long-does-it-take-for-you-to-respond-to-support-tickets': { topic: ['about'] },
  'where-can-i-find-a-non-technical-explanation-of-how-open-alex-works': { topic: ['about'] },

  'how-does-author-name-disambiguation-work': { topic: ['how-we-build-it'], entity: ['authors'] },
  'how-do-you-match-affiliations-to-institutions': { topic: ['how-we-build-it'], entity: ['institutions'] },
  'how-do-you-decide-if-an-article-is-open-access': { topic: ['how-we-build-it'], entity: ['works'] },
  'how-do-preprints-get-linked-to-published-versions': { topic: ['how-we-build-it'], entity: ['works'] },
  'what-is-fwci-and-how-is-it-calculated': { topic: ['how-we-build-it'], entity: ['works'] },
  'why-are-some-authors-assigned-to-null-author-id': { topic: ['how-we-build-it'], entity: ['authors'] },
  'why-cant-i-find-the-right-publisher-for-a-journal-in-openalex': { topic: ['how-we-build-it'], entity: ['publishers', 'sources'] },
  'why-are-my-reference-counts-lower-than-expected': { topic: ['how-we-build-it'], entity: ['works'] },
  'why-does-the-abstract-field-have-text-that-isnt-part-of-the-abstract': { topic: ['how-we-build-it'], entity: ['works'] },

  'fix-errors-in-openalex': { topic: ['fixing-errors'] },
  'how-can-i-fix-errors-in-an-openalex-author-profile': { topic: ['fixing-errors'], entity: ['authors'] },
  'how-can-i-fix-errors-in-an-openalex-source-profile': { topic: ['fixing-errors'], entity: ['sources'] },
  'how-can-i-correct-institutional-affiliations-for-a-work': { topic: ['fixing-errors'], entity: ['institutions', 'works'] },
  'how-can-i-correct-the-open-access-status-of-journals-in-unpaywall': { topic: ['fixing-errors'], entity: ['sources'] },
  'what-are-alternate-names-and-how-i-do-change-them': { topic: ['fixing-errors'], entity: ['authors'] },
  'why-are-my-open-access-curation-requests-getting-rejected': { topic: ['fixing-errors'], entity: ['works'] },
  'why-is-the-date-field-wrong-and-how-can-i-fix-it': { topic: ['fixing-errors'], entity: ['works'] },
  'why-is-this-publication-labeled-as-closed-when-it-is-clearly-open-acce': { topic: ['fixing-errors'], entity: ['works'] },
  'i-think-my-institution-is-missing-works-in-openalex-what-can-i-do': { topic: ['fixing-errors'], entity: ['institutions', 'works'] },

  'how-can-i-get-my-journal-indexed-in-openalex': { topic: ['indexing'], entity: ['sources'] },
  'how-can-i-get-my-repository-indexed-in-openalex': { topic: ['indexing'], entity: ['sources'] },
  'why-are-only-some-of-my-repository-records-showing-up-in-openalex': { topic: ['indexing', 'how-we-build-it'], entity: ['sources'] },

  'how-do-i-find-a-publications-openalex-work-id': { topic: ['ids'], entity: ['works'], interface: ['web', 'api'] },
  'how-do-i-find-my-openalex-author-id': { topic: ['ids'], entity: ['authors'], interface: ['web'] },
  'how-do-i-find-the-openalex-source-id': { topic: ['ids'], entity: ['sources'], interface: ['web'] },
  'how-do-i-find-the-publisher-id-for-a-journals-host-organization': { topic: ['ids'], entity: ['publishers', 'sources'], interface: ['web'] },

  'how-do-i-find-the-most-cited-publications': { topic: ['searching'], entity: ['works'], interface: ['web', 'api'] },
  'how-do-i-limit-my-results-to-only-the-top-100-cited-publications': { topic: ['searching'], entity: ['works'], interface: ['web'] },
  'omit-retracted-works-from-my-analysis': { topic: ['searching'], entity: ['works'], interface: ['web', 'api'] },
  'is-there-a-limit-to-the-length-of-queries-in-openalex': { topic: ['searching'], interface: ['api'] },
  'where-can-i-find-information-about-which-issue-of-a-journal-an-article': { topic: ['searching'], entity: ['works'], interface: ['web', 'api'] },
  'why-are-the-counts-by-year-numbers-different-than-what-i-see-in-the-us': { topic: ['searching', 'how-we-build-it'], interface: ['api'] },

  'export-results-from-the-openalex-website': { topic: ['exporting'], entity: ['works'], interface: ['web'] },
  'how-do-i-import-openalex-data-into-vosviewer': { topic: ['exporting'], interface: ['web'] },
  'link-resolver-integrations': { topic: ['exporting'] },
  'why-does-the-unpaywall-plugin-say-this-paywalled-article-is-open-acces': { topic: ['exporting'], entity: ['works'] },

  'activate-your-admin-dashboard': { topic: ['supporters'], entity: ['institutions'] },
  'activate-the-affiliation-editor': { topic: ['supporters'], entity: ['institutions'] },
  'activate-unsub': { topic: ['supporters'] },
  'advisory-board-nominations': { topic: ['supporters'] },
  'quarterly-supporter-meetings': { topic: ['supporters'] },
};

export function helpFacetsFor(slug: string): HelpTags {
  return HELP_CARD_FACETS[slug] ?? {};
}

/** Facet set + tag lookup for a bucket tab (recipes | help). */
export function facetConfig(tab: string): { facets: Facet[]; tagsFor: (slug: string) => Partial<Record<string, string[]>> } | undefined {
  if (tab === 'recipes') return { facets: FACETS, tagsFor: facetsFor };
  if (tab === 'help') return { facets: HELP_FACETS, tagsFor: helpFacetsFor };
  return undefined;
}
