// Facet taxonomy + tags for the two "bucket" tabs (oxjob #354, Jason-approved
// 2026-07-28; FAQ added Pass U 2026-08-06). Recipes and FAQ are flat buckets
// of articles you filter, not curated hierarchies — facets are TAGS, not
// categories: a card carries 0..n values per facet. Filtering is OR within a
// facet, AND across facets.
//
// Lives here (not in content frontmatter) for the same reason as nav.ts: the
// content files are regenerated by the migration scripts, and slugs are the
// stable key. Values with zero cards still render (muted) — the library is
// growing and Agents/Snapshot recipes are coming.
//
// Terminology is deliberately OpenAlex-native ("Sources", "Aboutness") — we
// teach users our vocabulary as they go.
//
// The Entity and Interface axes are shared vocabulary between the two tabs
// (each tab lists only the values its articles use); Recipes' Task/Variable
// axes are analysis-shaped and don't fit FAQ articles, which get a Topic axis
// instead (Pass U call).

export interface FacetValue {
  id: string;
  label: string;
}
export interface Facet {
  key: string;
  label: string;
  values: FacetValue[];
}

// Pass W (2026-08-06): the "Task" facet (Count/Find/Fix/Map) was dropped — too
// abstract to be useful. Recipes now filter on Variable / Entity / Interface.
// (CARD_FACETS rows keep their `task` tags harmlessly; they're just not shown.)
export const FACETS: Facet[] = [
  {
    // Pass W.1: relabeled "Variable" → "Topic" so both how-to tabs share the
    // same axis names (Topic / Entity / Interface). Internal key stays
    // `variable` (CARD_FACETS + data-variable attrs unchanged).
    key: 'variable',
    label: 'Topic',
    values: [
      { id: 'output', label: 'Output volume' },
      { id: 'citations', label: 'Citations' },
      { id: 'open-access', label: 'Open Access' },
      { id: 'collaboration', label: 'Collaboration' },
      { id: 'aboutness', label: 'Aboutness' },
      { id: 'funding', label: 'Funding & costs' },
    ],
  },
  {
    key: 'entity',
    label: 'Entity',
    values: [
      { id: 'institutions', label: 'Institutions' },
      { id: 'authors', label: 'Authors' },
      { id: 'sources', label: 'Sources' },
      { id: 'funders', label: 'Funders' },
    ],
  },
  {
    key: 'interface',
    label: 'Interface',
    values: [
      { id: 'web', label: 'Web' },
      { id: 'api', label: 'API' },
      { id: 'oql', label: 'OQL' },
      { id: 'agents', label: 'Agents' },
      { id: 'snapshot', label: 'Snapshot' },
    ],
  },
];

type CardTags = Partial<Record<'task' | 'variable' | 'entity' | 'interface', string[]>>;

export const CARD_FACETS: Record<string, CardTags> = {
  // The site-wide Quick Start (moved in from Docs, Jason 2026-08-08): answers
  // one question three ways — website, API, agent.
  quickstart: {
    interface: ['web', 'api', 'agents'],
  },
  'analyze-a-funders-portfolio': {
    task: ['map'],
    variable: ['output'],
    entity: ['funders'],
    interface: ['api'],
  },
  'audit-an-author-profiles-works': {
    task: ['fix'],
    entity: ['authors'],
    interface: ['api'],
  },
  'break-down-of-my-institutions-outputs-by-subject-area-subfield': {
    task: ['count'],
    variable: ['output', 'aboutness'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'check-if-a-journals-works-are-in-openalex': {
    task: ['fix', 'count'],
    variable: ['output'],
    entity: ['sources'],
    interface: ['web'],
  },
  'count-incoming-citations-to-any-results-set': {
    task: ['count'],
    variable: ['citations'],
    interface: ['web'],
  },
  'estimate-the-apc-fees-my-institution-has-paid-to-make-research-open-ac': {
    task: ['count'],
    variable: ['funding', 'open-access'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'find-collaborators': {
    task: ['find'],
    variable: ['collaboration'],
    entity: ['authors', 'institutions'],
    interface: ['api'],
  },
  'find-most-cited-journals': {
    task: ['count', 'find'],
    variable: ['citations'],
    entity: ['institutions', 'sources'],
    interface: ['api'],
  },
  'how-many-of-each-type-of-output-does-my-institution-have': {
    task: ['count'],
    variable: ['output'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'how-many-outputs-does-my-institution-have': {
    task: ['count'],
    variable: ['output'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'how-much-is-my-institutions-work-cited': {
    task: ['count'],
    variable: ['citations'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'identify-other-institutions-that-collaborate-with-researchers-from-my': {
    task: ['find'],
    variable: ['collaboration'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'map-an-sdg-research-landscape': {
    task: ['map'],
    variable: ['aboutness'],
    interface: ['api'],
  },
  'quick-api-recipes': {
    task: ['count', 'find'],
    interface: ['api'],
  },
  'track-open-access-trends': {
    task: ['map', 'count'],
    variable: ['open-access'],
    interface: ['api'],
  },
  'what-percentage-of-my-institutions-outputs-are-open-access-oa': {
    task: ['count'],
    variable: ['open-access'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'which-journals-do-researchers-at-my-institution-publish-in': {
    task: ['count', 'find'],
    variable: ['output'],
    entity: ['institutions', 'sources'],
    interface: ['web'],
  },
  'which-of-my-institutions-outputs-are-contributions-to-un-sustainable-d': {
    task: ['count'],
    variable: ['aboutness'],
    entity: ['institutions'],
    interface: ['web'],
  },
  'systematic-reviews-with-oql': {
    task: ['find'],
    interface: ['oql', 'web', 'api'],
  },
  // Bulk-data + Unpaywall recipes (moved in from Docs, rewrite Pass H)
  'download-to-your-machine': {
    task: ['map'],
    interface: ['snapshot'],
  },
  'how-do-i-read-jsonl-files': {
    task: ['map'],
    interface: ['snapshot'],
  },
  'how-do-i-use-the-title-search-api': {
    task: ['find'],
    variable: ['open-access'],
    interface: ['api'],
  },
  'how-do-i-make-the-unpaywall-extension-work-on-my-site': {
    task: ['fix'],
    variable: ['open-access'],
    interface: ['web'],
  },
};

export function facetsFor(slug: string): CardTags {
  return CARD_FACETS[slug] ?? {};
}

// --- FAQ tab facets removed (oxjob #752) ---
// The help tab's flat facet bucket (HELP_FACETS / HELP_CARD_FACETS, #354
// Pass U) died with the How-to consolidation: 47 articles became ~12 task
// pages, grouped by topic in nav.ts (NAV_GROUPS.help) — a facet UI over 12
// items was chrome without power. Tutorials keeps the bucket pattern above.

/** Facet set + tag lookup for a bucket tab (recipes | help). */
export function facetConfig(tab: string): { facets: Facet[]; tagsFor: (slug: string) => Partial<Record<string, string[]>> } | undefined {
  if (tab === 'tutorials') return { facets: FACETS, tagsFor: facetsFor };
  return undefined;
}
